//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrganizationClient.CentralService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Supplier", Namespace="http://schemas.datacontract.org/2004/07/Contracts.Types")]
    [System.SerializableAttribute()]
    public partial class Supplier : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndPointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OrganizationClient.CentralService.Product[] ProductsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndPoint {
            get {
                return this.EndPointField;
            }
            set {
                if ((object.ReferenceEquals(this.EndPointField, value) != true)) {
                    this.EndPointField = value;
                    this.RaisePropertyChanged("EndPoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OrganizationClient.CentralService.Product[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/Contracts.Types")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OrganizationClient.CentralService.ProductFamily FamilyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OrganizationClient.CentralService.ProductFamily Family {
            get {
                return this.FamilyField;
            }
            set {
                if ((object.ReferenceEquals(this.FamilyField, value) != true)) {
                    this.FamilyField = value;
                    this.RaisePropertyChanged("Family");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductFamily", Namespace="http://schemas.datacontract.org/2004/07/Contracts.Types")]
    [System.SerializableAttribute()]
    public partial class ProductFamily : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContestInfo", Namespace="http://schemas.datacontract.org/2004/07/Contracts.Types")]
    [System.SerializableAttribute()]
    public partial class ContestInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OrganizationClient.CentralService.Organization OrganizationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OrganizationClient.CentralService.Product ProductField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OrganizationClient.CentralService.Organization Organization {
            get {
                return this.OrganizationField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganizationField, value) != true)) {
                    this.OrganizationField = value;
                    this.RaisePropertyChanged("Organization");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OrganizationClient.CentralService.Product Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Organization", Namespace="http://schemas.datacontract.org/2004/07/Contracts.Types")]
    [System.SerializableAttribute()]
    public partial class Organization : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EndPointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndPoint {
            get {
                return this.EndPointField;
            }
            set {
                if ((object.ReferenceEquals(this.EndPointField, value) != true)) {
                    this.EndPointField = value;
                    this.RaisePropertyChanged("EndPoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CentralService.ICentralSupplierService", CallbackContract=typeof(OrganizationClient.CentralService.ICentralSupplierServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface ICentralSupplierService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentralServiceForDualCommunication/SignIn", ReplyAction="http://tempuri.org/ICentralServiceForDualCommunication/SignInResponse")]
        void SignIn();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentralServiceForDualCommunication/SignIn", ReplyAction="http://tempuri.org/ICentralServiceForDualCommunication/SignInResponse")]
        System.Threading.Tasks.Task SignInAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsTerminating=true, IsInitiating=false, Action="http://tempuri.org/ICentralServiceForDualCommunication/SignOut", ReplyAction="http://tempuri.org/ICentralServiceForDualCommunication/SignOutResponse")]
        void SignOut();
        
        [System.ServiceModel.OperationContractAttribute(IsTerminating=true, IsInitiating=false, Action="http://tempuri.org/ICentralServiceForDualCommunication/SignOut", ReplyAction="http://tempuri.org/ICentralServiceForDualCommunication/SignOutResponse")]
        System.Threading.Tasks.Task SignOutAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentralSupplierService/RegisterSupplier", ReplyAction="http://tempuri.org/ICentralSupplierService/RegisterSupplierResponse")]
        bool RegisterSupplier(OrganizationClient.CentralService.Supplier supplier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentralSupplierService/RegisterSupplier", ReplyAction="http://tempuri.org/ICentralSupplierService/RegisterSupplierResponse")]
        System.Threading.Tasks.Task<bool> RegisterSupplierAsync(OrganizationClient.CentralService.Supplier supplier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentralSupplierService/UnregisterSupplier", ReplyAction="http://tempuri.org/ICentralSupplierService/UnregisterSupplierResponse")]
        bool UnregisterSupplier(string supplierName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentralSupplierService/UnregisterSupplier", ReplyAction="http://tempuri.org/ICentralSupplierService/UnregisterSupplierResponse")]
        System.Threading.Tasks.Task<bool> UnregisterSupplierAsync(string supplierName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICentralSupplierServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentralSupplierService/GetSupplierInfo", ReplyAction="http://tempuri.org/ICentralSupplierService/GetSupplierInfoResponse")]
        OrganizationClient.CentralService.Supplier GetSupplierInfo();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ICentralSupplierService/NewContest")]
        void NewContest(OrganizationClient.CentralService.ContestInfo contest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICentralSupplierServiceChannel : OrganizationClient.CentralService.ICentralSupplierService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CentralSupplierServiceClient : System.ServiceModel.DuplexClientBase<OrganizationClient.CentralService.ICentralSupplierService>, OrganizationClient.CentralService.ICentralSupplierService {
        
        public CentralSupplierServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public CentralSupplierServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public CentralSupplierServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public CentralSupplierServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public CentralSupplierServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void SignIn() {
            base.Channel.SignIn();
        }
        
        public System.Threading.Tasks.Task SignInAsync() {
            return base.Channel.SignInAsync();
        }
        
        public void SignOut() {
            base.Channel.SignOut();
        }
        
        public System.Threading.Tasks.Task SignOutAsync() {
            return base.Channel.SignOutAsync();
        }
        
        public bool RegisterSupplier(OrganizationClient.CentralService.Supplier supplier) {
            return base.Channel.RegisterSupplier(supplier);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterSupplierAsync(OrganizationClient.CentralService.Supplier supplier) {
            return base.Channel.RegisterSupplierAsync(supplier);
        }
        
        public bool UnregisterSupplier(string supplierName) {
            return base.Channel.UnregisterSupplier(supplierName);
        }
        
        public System.Threading.Tasks.Task<bool> UnregisterSupplierAsync(string supplierName) {
            return base.Channel.UnregisterSupplierAsync(supplierName);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CentralService.ICentralOrganizationService", CallbackContract=typeof(OrganizationClient.CentralService.ICentralOrganizationServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface ICentralOrganizationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentralServiceForDualCommunication/SignIn", ReplyAction="http://tempuri.org/ICentralServiceForDualCommunication/SignInResponse")]
        void SignIn();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentralServiceForDualCommunication/SignIn", ReplyAction="http://tempuri.org/ICentralServiceForDualCommunication/SignInResponse")]
        System.Threading.Tasks.Task SignInAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsTerminating=true, IsInitiating=false, Action="http://tempuri.org/ICentralServiceForDualCommunication/SignOut", ReplyAction="http://tempuri.org/ICentralServiceForDualCommunication/SignOutResponse")]
        void SignOut();
        
        [System.ServiceModel.OperationContractAttribute(IsTerminating=true, IsInitiating=false, Action="http://tempuri.org/ICentralServiceForDualCommunication/SignOut", ReplyAction="http://tempuri.org/ICentralServiceForDualCommunication/SignOutResponse")]
        System.Threading.Tasks.Task SignOutAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentralOrganizationService/CreateContest", ReplyAction="http://tempuri.org/ICentralOrganizationService/CreateContestResponse")]
        int CreateContest(string endPoint, OrganizationClient.CentralService.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentralOrganizationService/CreateContest", ReplyAction="http://tempuri.org/ICentralOrganizationService/CreateContestResponse")]
        System.Threading.Tasks.Task<int> CreateContestAsync(string endPoint, OrganizationClient.CentralService.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentralOrganizationService/GetPossibleSuppliers", ReplyAction="http://tempuri.org/ICentralOrganizationService/GetPossibleSuppliersResponse")]
        OrganizationClient.CentralService.Supplier[] GetPossibleSuppliers(int proposalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentralOrganizationService/GetPossibleSuppliers", ReplyAction="http://tempuri.org/ICentralOrganizationService/GetPossibleSuppliersResponse")]
        System.Threading.Tasks.Task<OrganizationClient.CentralService.Supplier[]> GetPossibleSuppliersAsync(int proposalId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICentralOrganizationServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICentralOrganizationService/GetOrganizationInfo", ReplyAction="http://tempuri.org/ICentralOrganizationService/GetOrganizationInfoResponse")]
        OrganizationClient.CentralService.Organization GetOrganizationInfo();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICentralOrganizationServiceChannel : OrganizationClient.CentralService.ICentralOrganizationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CentralOrganizationServiceClient : System.ServiceModel.DuplexClientBase<OrganizationClient.CentralService.ICentralOrganizationService>, OrganizationClient.CentralService.ICentralOrganizationService {
        
        public CentralOrganizationServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public CentralOrganizationServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public CentralOrganizationServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public CentralOrganizationServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public CentralOrganizationServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void SignIn() {
            base.Channel.SignIn();
        }
        
        public System.Threading.Tasks.Task SignInAsync() {
            return base.Channel.SignInAsync();
        }
        
        public void SignOut() {
            base.Channel.SignOut();
        }
        
        public System.Threading.Tasks.Task SignOutAsync() {
            return base.Channel.SignOutAsync();
        }
        
        public int CreateContest(string endPoint, OrganizationClient.CentralService.Product product) {
            return base.Channel.CreateContest(endPoint, product);
        }
        
        public System.Threading.Tasks.Task<int> CreateContestAsync(string endPoint, OrganizationClient.CentralService.Product product) {
            return base.Channel.CreateContestAsync(endPoint, product);
        }
        
        public OrganizationClient.CentralService.Supplier[] GetPossibleSuppliers(int proposalId) {
            return base.Channel.GetPossibleSuppliers(proposalId);
        }
        
        public System.Threading.Tasks.Task<OrganizationClient.CentralService.Supplier[]> GetPossibleSuppliersAsync(int proposalId) {
            return base.Channel.GetPossibleSuppliersAsync(proposalId);
        }
    }
}
